version: '3.8'

services:

  postgres:
    image: postgres:14.2
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=movierama
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    healthcheck:
      test: "pg_isready -U postgres"